### ISSUE TITLE
temporary publishing in Wikipedia

### ISSUE THREAD

**Issue by ETTMCR** [shahart/heb-microbit#3]
I wrote the article [מיקרוביט ](https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%A7%D7%A8%D7%95%D7%91%D7%99%D7%98)in the Wikipedia.
So, if it already work, even though it doesn't an official extension, Do you want me to publish there the extension URL  ?https://github.com/shahart/heb-microbit

**Comment by shahart** [comment]
Resolved
