### ISSUE TITLE
תמונת הבלוק 

### ISSUE THREAD

**Issue by ETTMCR** [shahart/heb-microbit#4]
תמונת הבלוק של קטקנה בהרחבה שלנו
![image](https://github.com/user-attachments/assets/586b3549-ac61-4f15-b5a0-4d6115907cfa)

**Comment by shahart** [comment]
can't repro

**Comment by ETTMCR** [comment]
I think it happens only when katakana ext' is in the system too.
repro - reproduced ?
 i.e. The make the bug / issue again ?
